version: "3.8"
services:
  app:
    image: tal_studio
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - NODE_ENV=$NODE_ENV
      - MONGO_URI=$MONGO_URI
      - SALT=$SALT
      - COOKIE_SECRET=$COOKIE_SECRET
      - USING_INTERNET=$USING_INTERNET
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
      - NODE_LOCAL_PORT=NODE_LOCAL_PORT
    stdin_open: true
    tty: true